"""Build src/brandThemes.js from awesome-design-md/design-md/<brand>/DESIGN.md."""
import re, glob, os, colorsys, json
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

def hsl(hex_):
    hex_ = hex_.lstrip('#')
    if len(hex_) == 3: hex_ = ''.join(c*2 for c in hex_)
    r, g, b = (int(hex_[i:i+2], 16)/255 for i in (0, 2, 4))
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h*360, s*100, l*100
def norm(h):
    h = h.lower().lstrip('#')
    if len(h) == 3: h = ''.join(c*2 for c in h)
    return '#' + h[:6]

NAMES = {
  'linear.app': 'Linear', 'x.ai': 'xAI', 'mistral.ai': 'Mistral', 'together.ai': 'Together',
  'opencode.ai': 'OpenCode', 'bmw-m': 'BMW M', 'bmw': 'BMW', 'hp': 'HP', 'ibm': 'IBM',
  'nvidia': 'NVIDIA', 'dell-1996': 'Dell 1996', 'nintendo-2001': 'Nintendo 2001',
  'elevenlabs': 'ElevenLabs', 'clickhouse': 'ClickHouse', 'hashicorp': 'HashiCorp',
  'mongodb': 'MongoDB', 'posthog': 'PostHog', 'runwayml': 'Runway', 'spacex': 'SpaceX',
  'theverge': 'The Verge', 'voltagent': 'VoltAgent', 'playstation': 'PlayStation',
  'minimax': 'MiniMax', 'cal': 'Cal.com', 'clay': 'Clay', 'wise': 'Wise',
}
# the ten files without a colors: block — canvas / accent chosen by hand from their text
MANUAL = {
  'kraken': dict(light='#ffffff', dark='#120b2a', accent='#7132f5'),
  'lamborghini': dict(dark='#000000', accent='#ffc000'),
  'lovable': dict(light='#f7f4ed', dark='#1c1c1c', accent='#f0562a'),
  'mastercard': dict(light='#f3f0ee', dark='#141413', accent='#eb001b'),
  'runwayml': dict(dark='#030303', accent='#767d88'),
  'sanity': dict(dark='#0b0b0b', accent='#f03e2f'),
  'spotify': dict(dark='#121212', accent='#1ed760'),
  'starbucks': dict(light='#f2f0eb', dark='#1e3932', accent='#00754a'),
  'tesla': dict(light='#ffffff', dark='#171a20', accent='#3e6ae1'),
  'theverge': dict(dark='#131313', accent='#3cffd0'),
  'sentry': dict(dark='#181225', light='#ffffff', accent='#7553ff'),
}
DARK_KEYS = ['canvas-dark', 'surface-dark', 'inverse-canvas', 'charcoal', 'surface-strong', 'ink-deep', 'ink']
LIGHT_KEYS = ['canvas-light', 'inverse-canvas', 'canvas-soft', 'surface-soft', 'surface-card', 'on-primary']

out = []
for f in sorted(glob.glob('awesome-design-md/design-md/<brand>/DESIGN.md')):
    slug = f.replace('\\', '/').split('/')[-2]
    name = NAMES.get(slug, slug.replace('-', ' ').title())
    s = open(f, encoding='utf-8').read()
    m = re.search(r'^colors:\n((?:[ \t]+.*\n)+)', s, re.M)
    if m:
        kv = {k: norm(v) for k, v in re.findall(r'^\s+([\w-]+):\s*"?(#[0-9a-fA-F]{3,8})', m.group(1), re.M)}
        canvas = kv.get('canvas') or kv.get('surface-1') or kv.get('surface') or kv.get('canvas-dark') or kv.get('canvas-light')
        accent = kv.get('primary') or kv.get('accent')
        if (not canvas or not accent) and slug in MANUAL:
            canvas = None
        elif not canvas or not accent:
            print('skip', slug, list(kv)[:6]); continue
    if m and canvas:
        cl = hsl(canvas)[2]
        dark = light = None
        if cl < 45:
            dark = canvas
            for k in LIGHT_KEYS:
                if k in kv and hsl(kv[k])[2] > 88: light = kv[k]; break
        else:
            light = canvas
            for k in DARK_KEYS:
                if k in kv and hsl(kv[k])[2] < 30: dark = kv[k]; break
        t = dict(dark=dark, light=light, accent=accent)
        # a neutral "primary" (white / black buttons) carries no colour — prefer a saturated brand colour if the file has one
        ah, as_, al = hsl(t['accent'])
        if as_ < 15 or al > 85:
            skip = ('primary', 'on-primary', 'success', 'error', 'warning', 'info', 'semantic', 'link')
            alt = [v for k, v in kv.items() if not any(x in k for x in skip) and 22 < hsl(v)[2] < 78 and hsl(v)[1] > 45]
            if alt: t['accent'] = alt[0]
            elif al > 85: t['accent'] = '#d4af37'
    else:
        t = MANUAL[slug]
    entry = {'id': 'brand-' + re.sub(r'[^a-z0-9]+', '-', slug), 'name': name, 'accent': t['accent'], 'brand': True, 'flat': True}
    if t.get('dark'): entry['hex'] = t['dark']
    if t.get('light') and hsl(t['light'])[2] > 80: entry['light'] = t['light']
    if 'hex' not in entry and 'light' not in entry:
        print('skip (no base)', slug); continue
    out.append(entry)

lines = [json.dumps(e, ensure_ascii=False) for e in out]
js = ("/* Generated by extract_brands.py from awesome-design-md/design-md/<brand>/DESIGN.md\n"
      "   (brand colour systems used purely as colour inspiration). Each entry:\n"
      "   hex = dark canvas, light = light canvas (either may be absent), accent = brand primary. */\n"
      "export const BRAND_THEMES = [\n" + ''.join('  ' + l + ',\n' for l in lines) + "]\n")
open('src/brandThemes.js', 'w', encoding='utf-8').write(js)
print(len(out), 'brand themes written')
for e in out: print(e['name'], e.get('hex'), e.get('light'), e['accent'])
